LANG_CODES={
    "en":"English",
    "de":"German",
    "fr":"French",
    "es":"Spanish",
    "hi":"Hindi",
}
MODEL_NAME={
    ("en","de"):"Helsinki-NLP/opus-mt-en-de",
    ("de","en"):"Helsinki-NLP/opus-mt-de-en",
    ("en","fr"):"Helsinki-NLP/opus-mt-en-fr",
    ("fr","en"):"Helsinki-NLP/opus-mt-fr-en",
    ("en","es"):"Helsinki-NLP/opus-mt-en-es",
    ("es","en"):"Helsinki-NLP/opus-mt-es-en",
    ("en","hi"):"Helsinki-NLP/opus-mt-en-hi",
    ("hi","en"):"Helsinki-NLP/opus-mt-hi-en",
}
